### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by aymericzip** [xavcochran/HelixDB#356]
### What happened?

I tried to set up Helix to experiment and met error by setting up the dockers containers.

I tried to follow this docs 

https://docs.helix-db.com/guides/deploying

```bash 
docker build -t helix-db .

[+] Building 2.2s (13/14)                                                                                                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 675B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                           2.1s
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 1.24kB                                                                                                                     0.0s
 => CANCELED [ 1/10] FROM docker.io/library/python:3.9@sha256:b93ed1cb6815be1d99908ab629d49680be28024c4183611ded45c425ecf7b907                          0.0s
 => => resolve docker.io/library/python:3.9@sha256:b93ed1cb6815be1d99908ab629d49680be28024c4183611ded45c425ecf7b907                                     0.0s
 => => sha256:b93ed1cb6815be1d99908ab629d49680be28024c4183611ded45c425ecf7b907 9.03kB / 9.03kB                                                          0.0s
 => => sha256:7cf997729dea0a13755affe001c7d779368a03e34445dff0bcb910a2d6fa9ec1 2.32kB / 2.32kB                                                          0.0s
 => => sha256:8c4f8c812d44d2fb2c660f2d4db1bdf36fe66ba5127635d7466f339b6720cca3 6.16kB / 6.16kB                                                          0.0s
 => [internal] load build context                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                         0.0s
 => CACHED [ 2/10] WORKDIR /code                                                                                                                        0.0s
 => CACHED [ 3/10] RUN apt-get update && apt-get install -y     curl     git     build-essential     pkg-config     libssl-dev     && rm -rf /var/lib/  0.0s
 => ERROR [ 4/10] COPY backend/requirements.txt /code/requirements.txt                                                                                  0.0s
 => CACHED [ 5/10] RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt                                                                   0.0s
 => CACHED [ 6/10] RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y                                                          0.0s
 => CACHED [ 7/10] RUN curl -sSL "https://install.helix-db.com" | bash                                                                                  0.0s
 => CACHED [ 8/10] RUN helix install                                                                                                                    0.0s
 => ERROR [ 9/10] COPY backend /code/                                                                                                                   0.0s
------
 > [ 4/10] COPY backend/requirements.txt /code/requirements.txt:
------
------
 > [ 9/10] COPY backend /code/:
------
Dockerfile:24
--------------------
  22 |     RUN helix install
  23 |     
  24 | >>> COPY backend /code/
  25 |     
  26 |     RUN helix deploy
--------------------
ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref 29deb607-0920-4604-97d1-37ee44318215::pp1ausmddd9qswwl162flobus: "/backend": not found
```

I guess that the doc s not up to date

---

As a result, I cloned the main repo and tried to run the base Dockerfile 

In that case the container build, but an external dependency looks as missing

```ts
docker build -t helix-container .

[+] Building 2.3s (10/10) FINISHED                                                                                                      docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 636B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/rust:1.84                                                                                            1.5s
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 154B                                                                                                                       0.0s
 => [1/5] FROM docker.io/library/rust:1.84@sha256:738ae99a3d75623f41e6882566b4ef37e38a9840244a47efd4a0ca22e9628b88                                      0.0s
 => [internal] load build context                                                                                                                       0.1s
 => => transferring context: 2.76MB                                                                                                                     0.1s
 => CACHED [2/5] RUN apt-get update && apt-get install -y     clang     llvm-dev     gcc     g++     ca-certificates     && rm -rf /var/lib/apt/lists/  0.0s
 => CACHED [3/5] WORKDIR /usr/src/app                                                                                                                   0.0s
 => [4/5] COPY . .                                                                                                                                      0.0s
 => [5/5] RUN useradd -m user &&     chown -R user:user /usr/src/app                                                                                    0.5s
 => exporting to image                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                 0.0s
 => => writing image sha256:d6e080b562e56ebc8db9eb104d4237754a8d829de94bb4bdabc08f78fd9ae09d                                                            0.0s
 => => naming to docker.io/library/helix-container                                                                                                      0.0s

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview 
```

```bash
docker run -p 8000:8000 helix-container
error: failed to parse manifest at `/usr/src/app/helix-container/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.84.1 (66221abde 2024-11-19)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

<img width="628" height="342" alt="Image" src="https://github.com/user-attachments/assets/2b70d89c-ba0d-4c99-8354-b81a0e8d00fb" />

### Steps to reproduce

Problem 1:
1. copy - past the Dockerfile provided in the documentation 
2. run `docker build -t helix-db .`

Problem 2:
1. Clone the repo `git clone git@github.com:HelixDB/helix-db.git helix-db`
2. Build container `docker build -t helix-container .`
3. Start the container `docker run helix-container`

### Version

unkown

### Environment

Self-hosted

### Relevant log output

```shell

```

**Comment by xav-db** [comment]
Thanks for this will look into this and fix @putt-t, would be good to have your insight on this

**Comment by Nishant891** [comment]
You can try upgrading rust to a newer version.

Dockerfile
`FROM rust:1.85  # from 1.84 to 1.85 which supports edition2024`

Or Use Rust Nightly
`FROM rust:nightly  # definitely supports edition2024, can be unstable though`

**Comment by xav-db** [comment]
That will likely be it, I think we're saying we need rust version 1.88.0 but not sure if this is the same as in docker

**Comment by aymericzip** [comment]
thanks @Nishant891 it works !

Moving to the next error:

```bash 
docker run helix-container
warning: /usr/src/app/helix-db/Cargo.toml: file `/usr/src/app/helix-db/benches/bm25_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `bm25_benches`
  * `bench` target `bm25_benches`
warning: /usr/src/app/helix-db/Cargo.toml: file `/usr/src/app/helix-db/benches/hnsw_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `hnsw_benches`
  * `bench` target `hnsw_benches`
    Updating crates.io index
 Downloading crates ...
  Downloaded core_affinity v0.8.3
  Downloaded autocfg v1.4.0
  Downloaded bytemuck v1.22.0
  Downloaded icu_provider_macros v1.5.0
  [...]
   Compiling h2 v0.4.8
   Compiling icu_normalizer v1.5.0
   Compiling chrono v0.4.41
   Compiling crypto-common v0.1.6
   Compiling aead v0.5.2
   Compiling idna_adapter v1.2.0
   Compiling idna v1.0.3
   Compiling heed-types v0.21.0
   Compiling url v2.5.4
   Compiling tempfile v3.20.0
   Compiling tokio-native-tls v0.3.1
   Compiling hyper v1.6.0
   Compiling hyper-util v0.1.10
   Compiling hyper-tls v0.6.0
   Compiling axum v0.8.4
   Compiling reqwest v0.12.15
   Compiling helix-db v1.0.133 (/usr/src/app/helix-db)
error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/traversal_core/config.rs:214:12
    |
214 |         if let Some(data) = INTROSPECTION_DATA.get()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/traversal_core/config.rs:215:16
    |
215 |             && let Ok(stringified) = sonic_rs::to_string_pretty(data)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/traversal_core/ops/source/add_n.rs:99:12
   |
99 |         if let Some(bm25) = &self.storage.bm25
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/traversal_core/ops/source/add_n.rs:100:16
    |
100 |             && let Some(props) = node.properties.as_ref() {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/traversal_core/ops/util/drop.rs:28:32
   |
28 | ...                   if let Some(bm25) = &storage.bm25
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/traversal_core/ops/util/drop.rs:29:36
   |
29 | ...                   && let Err(e) = bm25.delete_doc(txn, node.id) {
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/traversal_core/ops/util/update.rs:59:36
   |
59 | ...                   if let Some(db) = storage.secondary_indices.get(key)
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/traversal_core/ops/util/update.rs:60:40
   |
60 | ...                   && let Some(old_value) = properties.get(key) {
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/traversal_core/ops/util/update.rs:128:28
    |
128 |                         if let Some(mut properties) = old_edge.properties.clone()
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/traversal_core/ops/util/update.rs:129:32
    |
129 | ...                   && let Some(ref props) = props {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/storage_core/version_info.rs:54:16
   |
54 |             && let Some(mut node_props) = node.properties.take()
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_engine/storage_core/version_info.rs:70:16
   |
70 |             && let Some(mut edge_props) = edge.properties.take()
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/vector_core/utils.rs:128:24
    |
128 |                     && let Ok(is_deleted) = item.check_property("is_deleted")
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/vector_core/utils.rs:129:28
    |
129 |                         && let Value::Boolean(is_deleted) = is_deleted.as_ref()
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helix_engine/vector_core/vector_core.rs:559:16
    |
559 |             if let Some(Value::Boolean(is_deleted)) = properties.get("is_deleted")
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helix_gateway/gateway.rs:80:12
   |
80 |         if let Ok(total_cores) = available_parallelism()
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/graph_step_validation.rs:363:16
    |
363 |             if let Some(ref ty) = sv.vector_type
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/infer_expr_type.rs:723:16
    |
723 |             if let Some(ref ty) = sv.vector_type
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/infer_expr_type.rs:992:16
    |
992 |             if let Some(ref ty) = bm25_search.type_arg
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/migration_validation.rs:133:16
    |
133 |             if let Some(default) = &default
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/migration_validation.rs:140:16
    |
140 |             if let Some(cast) = &cast
    |                ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helixc/analyzer/methods/query_validation.rs:41:12
   |
41 |         if let FieldType::Identifier(ref id) = param.param_type.1
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:90:51
   |
90 |   ...                   } else if let ValueType::Literal { ref value, ref loc } =
   |  _________________________________^
91 | | ...                       *value
   | |________________________________^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:293:16
    |
293 |             if let Some(ref ty) = sv.vector_type
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
    --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:1065:20
     |
1065 |                 if let Some(ref ty) = add.edge_type
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
    --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:1087:28
     |
1087 |                         if let Some(ty) = ty
     |                            ^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
    --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:1102:28
     |
1102 |                         if let Some(ty) = ty
     |                            ^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
    --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:1134:28
     |
1134 |                         if let Some(ty) = ty
     |                            ^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
    --> helix-db/src/helixc/analyzer/methods/traversal_validation.rs:1157:28
     |
1157 |                         if let Some(ty) = ty
     |                            ^^^^^^^^^^^^^^^^^
     |
     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `helix-db` (lib) due to 29 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by xav-db** [comment]
For this @aymericzip I think the rust version is out of date. The rust version needs to be >=1.88.0

**Comment by aymericzip** [comment]
Okk by bad

I was referring to your comment @Nishant891 
https://github.com/HelixDB/helix-db/issues/356#issuecomment-3206773084

It works well with the `FROM rust:1.88` instruction

I'm now able to run the app, thanks!

**Comment by xav-db** [comment]
Amazing that's great
