### ISSUE TITLE
HNSW vector search returns 'no entry point found' after storing vectors

### ISSUE THREAD

**Issue by lukmanha083** [xavcochran/HelixDB#801]
## Bug Description

After storing vectors in HelixDB and attempting to perform vector similarity search, the search fails with:

```
{"error":"Vector error: no entry point found for hnsw index","code":"GRAPH_ERROR"}
```

This occurs even after successfully storing hundreds of vectors. The HNSW index appears to not be initialized or the entry point is not being set.

## Environment

- **Helix Version**: v2.2.0
- **OS**: Linux (Arch Linux 6.17.9)
- **Docker**: Yes (local deployment via `helix push dev`)
- **Python Client**: helix-py

## Steps to Reproduce

1. Initialize fresh HelixDB instance:
```bash
helix stop dev
rm -rf .helix/.volumes/dev
helix push dev
```

2. Define vector schema in `schema.hx`:
```
V::ChunkVector {
    model_name: String,
    embedding_dim: U32,
}
```

3. Define search query in `queries.hx`:
```
SearchSimilar(query_vec: [F32], top_k: U64) =>
    MATCH (v:ChunkVector)
    WHERE v.embedding <COSINE_SIMILARITY> $query_vec
    RETURN v
    ORDER BY SCORE DESC
    LIMIT $top_k
```

4. Store vectors via Python client (651 vectors with 1536 dimensions from OpenAI embeddings)

5. Attempt vector search:
```python
from helix import Client
client = Client(local=True, port=6969)
results = client.run(SearchSimilar(query_vec=[...], top_k=3))
```

## Expected Behavior

Vector search should return the top-k most similar vectors.

## Actual Behavior

Search fails with HTTP 500:
```json
{"error":"Vector error: no entry point found for hnsw index","code":"GRAPH_ERROR"}
```

## Additional Context

- Keyword search (non-vector) queries work correctly
- Document/node storage works correctly
- The error persists after restarting HelixDB
- Clearing the database and re-ingesting does not resolve the issue
- The vectors appear to be stored (document stats show correct chunk count)

## Workaround

None found. Semantic/vector search is completely non-functional.

## Logs

No additional server-side logs available from Docker container.

**Comment by xav-db** [comment]
Looking into this now

**Comment by xav-db** [comment]
this hql query is not valid? are you sure you are running this:<br><br>SearchSimilar(query_vec: \[F32\], top_k: U64) =>
    MATCH (v:ChunkVector)
    WHERE v.embedding <COSINE_SIMILARITY> $query_vec
    RETURN v
    ORDER BY SCORE DESC
    LIMIT $top_k

**Comment by lukmanha083** [comment]
Apologies, I included incorrect query syntax in my initial report. Here's the actual query from our `queries.hx`:

```hql
QUERY SearchSimilar(query_vec: [F64], top_k: U32) =>
    results <- SearchV<ChunkVector>(query_vec, top_k)
    RETURN results
```

And the vector type definition in `schema.hx`:

```hql
V::ChunkVector {
    model_name: String,
    embedding_dim: U32,
}
```

The Python code calling this:

```python
from src.storage.queries import SearchSimilarChunks
# ... 
results = self.client.run(SearchSimilarChunks(query_vec=query_embedding, top_k=top_k))
```

The error occurs when calling `SearchV<ChunkVector>` after storing vectors. Is there something wrong with how we're using `SearchV`?

**Comment by lukmanha083** [comment]
Here's how we store vectors:

**Storage query:**
```hql
QUERY AddChunkVector(embedding: [F64], model_name: String, embedding_dim: U32) =>
    vec <- AddV<ChunkVector>(embedding, {
        model_name: model_name,
        embedding_dim: embedding_dim
    })
    RETURN vec
```

**Linking to chunk:**
```hql
QUERY LinkChunkVector(chunk_id: ID, vector_id: ID) =>
    chunk <- N<Chunk>(chunk_id)
    vec <- V<ChunkVector>(vector_id)
    AddE<HasEmbedding>::From(chunk)::To(vec)
    RETURN chunk
```

We store 1536-dimensional vectors (OpenAI text-embedding-3-small). After storing 651 vectors successfully (no errors), the `SearchV<ChunkVector>` call fails with the HNSW entry point error.

Is there additional configuration needed for the HNSW index, or should it be auto-initialized on first vector insertion?

**Comment by xav-db** [comment]
did you have data already stored in helix before updating to 2.2.0 or has this happened starting with an empty database after updating to 2.2.0

**Comment by lukmanha083** [comment]
Yes, we had data stored before updating to v2.2.0. Here's the timeline:

1. Had existing data on v2.1.10 (test documents, vectors from previous development)
2. Updated to v2.2.0 via `helix update`
3. Ran `helix push dev` which rebuilt the container
4. Tried vector search → got HNSW error
5. Tried clearing database with `kidkazz db clear --force` (our CLI wrapper) → still got error
6. Tried full reset: `helix stop dev && rm -rf .helix/.volumes/dev && helix push dev` → fresh database
7. Ingested new data (651 vectors) into the fresh database
8. Tried vector search → still got same HNSW error

So the issue persists even after completely removing the data volume and starting fresh post-update to v2.2.0.

Would it help if I tried downgrading back to v2.1.10 to test if the issue is specific to v2.2.0?

**Comment by xav-db** [comment]
okay thanks for this information debugging now

**Comment by xav-db** [comment]
This would be helpful yes

> Would it help if I tried downgrading back to v2.1.10 to test if the issue is specific to v2.2.0?

**Comment by lukmanha083** [comment]
Tried downgrading to v2.1.10 but our queries aren't backward compatible. The compilation fails with:

```
error[E0061]: this method takes 6 arguments but 5 arguments were supplied
```

Multiple instances of this error - appears the internal API changed between v2.1.10 and v2.2.0.

Our queries were developed against v2.2.0 so I can't easily test v2.1.10 without rewriting them.

Is there a way to debug what's happening with the HNSW index on v2.2.0? Or could this be related to the API changes that were made?

**Comment by xav-db** [comment]
ah okay no worries

**Comment by xav-db** [comment]
looking into it now will get back to you !

**Comment by xav-db** [comment]
Are you using upsert at all?

**Comment by xav-db** [comment]
@lukmanha083 would you also be able to share full hql schema, queries and helix.toml please

**Comment by lukmanha083** [comment]
No, we are not using upsert. We only use `AddN`, `AddV`, and `AddE` for creating nodes, vectors, and edges.

Here are the full HQL files:

**Gist with schema.hx, queries.hx, and helix.toml:**
https://gist.github.com/lukmanha083/b67f29c53625f73991eec4575c703434

**Summary of vector operations we use:**

**Adding vectors:**
```hql
QUERY AddChunkVector(embedding: [F64], model_name: String, embedding_dim: U32) =>
    vec <- AddV<ChunkVector>(embedding, {
        model_name: model_name,
        embedding_dim: embedding_dim
    })
    RETURN vec
```

**Searching vectors:**
```hql
QUERY SearchSimilar(query_vec: [F64], top_k: U32) =>
    results <- SearchV<ChunkVector>(query_vec, top_k)
    RETURN results
```

**Vector type definitions:**
```hql
V::ChunkVector {
    model_name: String,
    embedding_dim: U32,
}

V::TableVector {
    model_name: String,
    embedding_dim: U32,
}

V::SummaryVector {
    model_name: String,
    embedding_dim: U32,
}
```

We store 1536-dimensional vectors from OpenAI's text-embedding-3-small model.

**Comment by xav-db** [comment]
did the recent update fix things for you? i tried your queries and schema from fresh and inserted the same number of vectors and it worked fine.

**Comment by lukmanha083** [comment]
## Update - v2.2.1 Still Has Issue

Updated to Helix CLI v2.2.1 and performed a completely fresh test:

```bash
# Updated helix
helix update  # Now at v2.2.1

# Fresh database
helix stop dev
docker rm -f kidkazz_rag-dev
helix push dev  # Builds fresh container with v2.2.1

# Ingested test document  
kidkazz ingest markdown Inventory_Accounting.md --tags inventory,accounting
# Result: 651 chunks stored, embeddings generated successfully

# Test semantic search
kidkazz search semantic "FIFO inventory valuation" --top-k 3
# Result: FAILS with same HNSW error
```

**Error persists:**
```
{"error":"Vector error: no entry point found for hnsw index","code":"GRAPH_ERROR"}
```

**Keyword search works fine** (95 results for "FIFO"), so the chunks and text are stored correctly. Only vector similarity search is broken.

You mentioned it worked for you on a fresh install - could there be something specific to our schema or queries? Here's the gist again with our full files: https://gist.github.com/lukmanha083/b67f29c53625f73991eec4575c703434

Happy to try any debugging steps or share additional info.

**Comment by lukmanha083** [comment]
## Important Debugging Update - Root Cause Identified

After extensive testing, I've isolated the issue:

### Test Results Summary

| Test | Schema | Instance | Result |
|------|--------|----------|--------|
| Vector-only (8-dim) | Just `V::TestVector` | Fresh test port 6970 | **WORKS** |
| Graph+Vector | Nodes + Vectors + Edges | Fresh test port 6971 | **WORKS** |
| Multiple Vector Types | 3 vector types | Fresh test port 6972 | **WORKS** |
| 1536-dim vectors | OpenAI embeddings | Fresh test port 6973 | **WORKS** |
| 651 vectors (1536-dim) | Exact production schema | Fresh test port 6974 | **WORKS** |
| Same schema via CLI ingest | Exact production schema | Production port 6969 | **FAILS** |
| Manual add after CLI ingest | Same schema | Production port 6969 | **WORKS** |

### Key Finding

After CLI ingests 651 vectors, they are stored (documents/chunks are queryable) but **NOT indexed in HNSW**. However, if I manually add vectors afterwards using the same API endpoint (`AddChunkVector`), those new vectors ARE indexed and searchable.

```python
# CLI stores 651 vectors - model_name='text-embedding-3-small'
# Search returns: 'no entry point found for hnsw index'

# Manually add 1 vector via requests.post()
# Now search WORKS but ONLY returns the manual vector

# Add 50 more vectors via Python helix client
# All 51 manual vectors are searchable
# The 651 CLI vectors are STILL not searchable
```

### What This Suggests

1. The HNSW index entry point is NOT being initialized on the first batch of `AddV<ChunkVector>` calls during CLI ingestion
2. Once a manual vector is added later, the entry point gets set
3. But the original 651 vectors remain orphaned - stored but not in the HNSW index

### Request

Could you check if there's a race condition or timing issue with HNSW entry point initialization when:
- Many vectors are added rapidly in sequence (our CLI adds ~20 vectors/second)
- The database is fresh/empty when vectors start being added

Our CLI uses the exact same `AddChunkVector` query that works when called manually, so the issue seems to be related to the initial index creation timing.

**Comment by xav-db** [comment]
I think this must mean that it is something to do with how you are ingesting stuff via your CLI. would you be able to share how you're ingesting stuff via the cli?

**Comment by lukmanha083** [comment]
## CLI Ingestion Code

Here's how we ingest via CLI. The key method is `store_chunks` in our storage client:

```python
# src/storage/client.py - store_chunks method

def store_chunks(self, embedded_chunks, metadata_list, doc_id, title, tags):
    # Add document node first
    doc_query = AddDocument(doc_id, title, len(embedded_chunks), tags=tags)
    doc_response = self._client.query(doc_query)
    doc_internal_id = self._extract_node_id(doc_response)

    chunk_id_map = {}

    # Add chunks with their embeddings - sequential loop
    for ec, meta in zip(embedded_chunks, metadata_list):
        # 1. Add chunk node
        chunk_props = chunk_to_helix_node(ec.chunk, meta)
        chunk_query = AddChunk(chunk_props)
        chunk_response = self._client.query(chunk_query)
        chunk_internal_id = self._extract_node_id(chunk_response)

        if chunk_internal_id:
            chunk_id_map[ec.chunk.id] = chunk_internal_id

        # 2. Link document to chunk
        if doc_internal_id and chunk_internal_id:
            link_query = LinkDocumentChunk(doc_internal_id, chunk_internal_id)
            self._client.query(link_query)

        # 3. Store vector embedding if chunk has one
        if ec.embedding and chunk_internal_id:
            vec_query = AddChunkVector(
                embedding=ec.embedding,           # list[float], 1536 dims
                model_name=ec.model_name,         # 'text-embedding-3-small'
                embedding_dim=ec.embedding_dim,   # 1536
            )
            vec_response = self._client.query(vec_query)
            vec_internal_id = self._extract_node_id(vec_response)

            # 4. Link chunk to its embedding vector
            if vec_internal_id:
                link_vec_query = LinkChunkVector(chunk_internal_id, vec_internal_id)
                self._client.query(link_vec_query)

    # Add relationship edges after all chunks are stored
    for ec in embedded_chunks:
        # Parent-child and sibling relationships...
        pass

    return chunk_id_map
```

### Query Classes

```python
# src/storage/queries.py

class AddChunkVector(_get_query_base_class()):
    def __init__(self, embedding: list[float], model_name: str, embedding_dim: int):
        super().__init__(endpoint='AddChunkVector')
        self.embedding = embedding
        self.model_name = model_name
        self.embedding_dim = embedding_dim

    def query(self) -> list[dict]:
        return [{
            'embedding': self.embedding,
            'model_name': self.model_name,
            'embedding_dim': self.embedding_dim,
        }]
```

### Key Characteristics

1. **Sequential processing**: Each chunk is processed one at a time in a loop
2. **~651 vectors** added for a typical document
3. **Rate**: About 15-20 vectors/second (limited by network round-trips)
4. **helix-py version**: 0.2.31
5. **Each AddChunkVector is followed by LinkChunkVector** (edge from Chunk node to ChunkVector)

### HelixQL Query (from queries.hx)

```hql
QUERY AddChunkVector(embedding: [F64], model_name: String, embedding_dim: U32) =>
    vec <- AddV<ChunkVector>(embedding, {
        model_name: model_name,
        embedding_dim: embedding_dim
    })
    RETURN vec
```

Let me know if you need any other details!

**Comment by lukmanha083** [comment]
## Update - Issue Resolved ✅

After extensive debugging, I've identified and fixed the issue. **The HNSW search IS working in Helix v2.2.2** - the problem was on our client-side response parsing.

### Root Cause

Our `AddChunk` and `AddDocument` Python query classes had `response()` methods that were returning **static fallback data** instead of the actual Helix response:

```python
# BEFORE (broken):
def response(self, response: Any) -> QueryResult:
    return QueryResult(success=True, data={"chunk_id": self.chunk_props.get("chunk_id")})
```

This meant when we called `LinkChunkVector(chunk_id, vector_id)` to create `HasEmbedding` edges, the `chunk_id` was the user-facing string ID (e.g., "doc_l2_1") instead of the internal Helix node ID. Since the edge creation expected internal IDs, **no edges were being created** between chunks and their vectors.

### The Fix

1. **Updated response methods** to return actual Helix responses with internal IDs:

```python
# AFTER (fixed):
def response(self, response: Any) -> QueryResult:
    # Response format: {"chunk": {...node data with 'id'...}}
    if isinstance(response, dict) and 'chunk' in response:
        return QueryResult(success=True, data=response)
    return QueryResult(success=True, data={"chunk_id": self.chunk_props.get("chunk_id")})
```

2. **Updated `_extract_node_id()`** to handle nested response structures like `{"chunk": {"id": "..."}}`:

```python
for key in ['chunk', 'vec', 'doc', 'node', 'N']:
    if key in data and isinstance(data[key], dict):
        node_id = data[key].get('id') or data[key].get('Id')
        if node_id:
            return str(node_id)
```

3. **Added edge traversal for search results**. Since `SearchSimilar` returns ChunkVector nodes, we added a query to traverse back to chunks:

```hql
QUERY GetChunkForVector(vector_id: ID) =>
    chunk <- V<ChunkVector>(vector_id)::In<HasEmbedding>
    RETURN chunk
```

### Verification

After the fix:
- ✅ Clean database ingestion (no duplicates)
- ✅ 201 storage tests pass
- ✅ 91 chunker/embedder tests pass
- ✅ Semantic search returns correct results with similarity scores

```
Search results for: deep learning neural networks
╭──────────────────────── #1 test_document_l2_8 0.331 ─────────────────────────╮
│ Deep learning uses neural networks with many layers...                       │
╰──────────────────────────── Level 2 | unknown ───────────────────────────────╯
```

### Summary

**This was entirely a client-side bug in our kidkazz_rag codebase, not a Helix issue.** The HNSW index was working correctly the whole time - we just weren't creating the edges properly due to incorrect response parsing.

Thank you @xav-db for your patience in helping debug this! Closing as resolved on our end.

**Comment by lukmanha083** [comment]
Closing - issue was on our client side, not Helix. See previous comment for details.
